" execute pathogen#infect()

" filetype plugin indent on
" syntax on

" set statusline+=%#warningmsg#
" set statusline+=%{SyntasticStatuslineFlag()}
" set statusline+=%*

" let g:syntastic_always_populate_loc_list = 1
" let g:syntastic_auto_loc_list = 1
" let g:syntastic_check_on_open = 1
" let g:syntastic_check_on_wq = 0

" set rtp+=/usr/local/lib/python2.7/dist-packages/powerline/bindings/vim/
" set laststatus=2
" set t_Co=256

set tabstop = 8
set expandtab
set shiftwidth = 4
set softtabstop = 4

set number
